require_relative "./basketball/version"
require_relative "./basketball/cli"
require_relative "./basketball/team_info"
require_relative "./basketball/team_scrapper"
require_relative "./basketball/player_scrapper"
